feat: improve segment edit
twynb/AudioStreamSplitting pull request #126
Opened 2023-10-04 14:17 UTC by chubetho

2023-10-09 19:43 UTC, twynb requested changes
LGTM, other than some minor changes.

other than those, is this still a draft or was that a misclick?

also: do i understand it correctly that the updatePeaks()/updateFilePeaks() functions and related data are used for generating the wavesurfer waveform display?

2023-10-09 19:43 UTC, twynb commented on src/frontend/components/ModalEditSegment.vue
> +function formatToMMSS(secs: number) {
this should be moved to a composable

2023-10-09 19:43 UTC, twynb commented on src/frontend/components/ProjectItem.vue
> +const blob = shallowRef<Blob>()
should have a more expressive name - audioBlob or something?

2023-10-10 18:56 UTC, chubetho commented on src/frontend/components/ModalEditSegment.vue
> +function formatToMMSS(secs: number) {
done

2023-10-10 18:58 UTC, chubetho commented
yeah, peaks here are for waveform. They are computed in client side so they are quite expensive. So I cached them. It will be nice if peaks can be computed at time when project is created

2023-10-10 19:01 UTC, chubetho commented
close #124

2023-10-10 21:14 UTC, twynb approved these changes
LGTM

2023-10-10 21:14 UTC, merged